# Generated by Django 5.1.4 on 2025-01-09 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0002_room"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reservation",
            name="box_name",
        ),
        migrations.RemoveField(
            model_name="reservation",
            name="student",
        ),
        migrations.AddField(
            model_name="reservation",
            name="room",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="reservations.room",
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="student",
            name="email",
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name="student",
            name="student_number",
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
