# Generated by Django 5.1.4 on 2025-01-24 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0004_reservation_motif_reservation_participants_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reservation",
            name="participants",
        ),
        migrations.AddField(
            model_name="reservation",
            name="participant",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
