# Generated by Django 5.1.4 on 2025-01-24 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0005_remove_reservation_participants_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="reservation",
            old_name="participant",
            new_name="participants",
        ),
    ]
