# Generated by Django 5.1.4 on 2025-01-24 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0006_rename_participant_reservation_participants"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="name",
            field=models.CharField(
                choices=[("box a", "Box A"), ("box b", "Box B")], max_length=100
            ),
        ),
    ]
